### ISSUE TITLE
lightning talk

### ISSUE THREAD

**Issue by berlintam** [rubycorns/organization#7]
![rubycorns2](https://cloud.githubusercontent.com/assets/4237285/8943332/aa902ea0-357a-11e5-96af-6acaf1cf5347.jpg)
![rubycorns3](https://cloud.githubusercontent.com/assets/4237285/8943333/ad998dbc-357a-11e5-84e9-746eaf086663.jpg)

![rubycorns](https://cloud.githubusercontent.com/assets/4237285/8941373/6ae51316-356f-11e5-80f8-161be78e7528.jpg)

**Comment by sareg0** [comment]
i am loving on these photos. MOOAARRRR @BriocheBerlin do you think you could attach a few of your onesies photos... particularly the one of me pointing... I am thinking of making a 'we need you' poster style thing.

In any case, Tobi recommended we do the lightning talk on Saturday, because then there will be lots of time for people to come up to us Saturday and Sunday and ask about what we do.

So I'm thinking that the theme for the lightning talk will be a bit of a mix between learning groups in general, but also our experiences and journey as Rubycorns

**Life in a Learning Group
(or how we learned to stop worrying and build an app)**

The presentation will most likely be given in onesies.

I am in to do it, who else will join me? @PragTob, @berlintam and @lislis at least? @BriocheBerlin @FrauBienenstich also you two?

**Comment by lislis** [comment]
I am so in! Also so much :heart: for the title! Last year there were no slides so maybe we should write the title on a sign and hold it up? Are props allowed?

**Comment by sareg0** [comment]
apparently there will be a projector this year, but just minimizing tools, and go with a good 'ol sign would also be fine

Perhaps one with glitter?

**Comment by FrauBienenstich** [comment]
![img_20150616_203244](https://cloud.githubusercontent.com/assets/4237290/8955258/53adabf0-35eb-11e5-9224-82790a28c35a.jpg)

isn't that lovely?

**Comment by berlintam** [comment]
please don't use that one though.

**Comment by lislis** [comment]
@FrauBienenstich quit the trolling, this is serious business ;)

**Comment by FrauBienenstich** [comment]
don't feel like like i am true corn these days since i am hardly ever there. but i'll cheer for u from the audience!

**Comment by lislis** [comment]
@FrauBienenstich once a corn, always a corn!
@sareg0 yay for projectors! 
Then some slides to entertain the people. Content suggestions? I'd like to make at least the following points for study groups in general:
- Try to really meet regularly, especially in the beginning so people have time to adjust to meeting and make it a habit
- Work on a project together that interests everyone instead of everyone working on their own stuff
- Have at least two coaches
- Figure out a communication channel that works for everyone

Thoughts on working on our app?

**Comment by berlintam** [comment]
are we just going to talk about ourselves & how to make a project group?
Or are we going to invite ppl to join ours?
Or are we going to talk about rorganize?

ps: i am in

**Comment by sareg0** [comment]
We can make the point that we i.e. you all chose to work on an app together, that benefited the community and taught you a lot. That will fit with lisa's point about 'work on something' that interests everyone. We should promote rorganize.it, and tell people, this is where we meet and when. Come along. Also we will hand out tattoos as that has our details on it. 

I am happy to put together a couple of slides, and the rest of us can edit it too. Where do we wanna do them up; google drive or something less... ahem... ya know ;)

**Comment by lislis** [comment]
I will most probably do a super quick lightning talk at the rails girls workshop on Friday to advertise our our group and rorganize.it and give away some tattoos. More announcement style.
For the lightning talk on Saturday I think having a structure of 'We are a project group and this is how we do it and this is what we learnt and this is what we built' would be nice. Wdyt?

**Comment by sareg0** [comment]
yep totes up for not doubling up work

**Comment by FrauBienenstich** [comment]
there should be smoar rubycorn pics on twitter, i think...just sayin'!

**Comment by berlintam** [comment]
also on da blog

**Comment by berlintam** [comment]
we totes did this https://twitter.com/search?f=images&vertical=default&q=%23rubycornsrule&src=typd

**Comment by sareg0** [comment]
lightning talk = success :)

**Comment by til** [comment]
Spectacular success even!
